export default [
  {
    id: 1,
    user_id: 1,
    item_name: "Apples",
    quantity: 5,
    unit: "ct",
    category: "Fruits",
    status: "available",
    threshold_qty: 2,
    expiration_date: "2025-04-10",
    threshold_alert: "2025-04-05",
  },
  {
    id: 2,
    user_id: 1,
    item_name: "Eggs",
    quantity: 2,
    unit: "ct",
    category: "Poultry",
    status: "low",
    threshold_qty: 2,
    expiration_date: "2025-04-08",
    threshold_alert: "2025-04-03",
  },
  {
    id: 3,
    user_id: 1,
    item_name: "Milk",
    quantity: 4,
    unit: "ltr",
    category: "Dairy",
    status: "available",
    threshold_qty: 1,
    expiration_date: "2025-04-07",
    threshold_alert: "2025-04-02",
  },
  {
    id: 4,
    user_id: 2,
    item_name: "Apples",
    quantity: 5,
    unit: "ct",
    category: "Fruits",
    status: "available",
    threshold_qty: 2,
    expiration_date: "2025-04-10",
    threshold_alert: "2025-04-05",
  },
  {
    id: 5,
    user_id: 2,
    item_name: "Eggs",
    quantity: 2,
    unit: "ct",
    category: "Poultry",
    status: "low",
    threshold_qty: 2,
    expiration_date: "2025-04-08",
    threshold_alert: "2025-04-03",
  },
  {
    id: 6,
    user_id: 2,
    item_name: "Milk",
    quantity: 4,
    unit: "ltr",
    category: "Dairy",
    status: "available",
    threshold_qty: 1,
    expiration_date: "2025-04-07",
    threshold_alert: "2025-04-02",
  },
];
